[package]
name = "files_organizer_per_year"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
chrono = "0.4.19"
clap = "2.33.3"
rand = "0.8"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
