name: main

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:

  fmt:
    runs-on: 'ubuntu-latest'
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.75'
      
      - name: Run Cargo Fmt
        run: cargo fmt

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust_version: ['1.75']
        os: ['windows-latest', 'ubuntu-latest']
        
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
      
      - name: Run Cargo Build    
        run: cargo test
