name: main

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.75"
          components: clippy

      - name: Run Cargo Fmt Check
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --check

      - name: Run Cargo Check
        uses: actions-rs/cargo@v1.0.1
        with:
          command: check

      - name: Run Cargo Clippy
        uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy

  build:
    name: Build
    runs-on: "ubuntu-latest"
    needs: [lint]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run Cargo Build
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: [build]
    strategy:
      matrix:
        rust_version: ["1.75", "1.76"]
        os: ["windows-latest", "ubuntu-latest"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}

      - name: Run Cargo Test
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
